import { Theming, ModeSelect, IsSet, ReactStylusProps, ColorsMode, ColorsByMode, StatusColors } from './types';
export declare class ReactStylus implements Theming {
    private colors?;
    private backgroundDark?;
    private backgroundLight?;
    private backgroundPale?;
    private textColorLight?;
    private textColorDark?;
    private textColorPale?;
    private tintColorLight?;
    private tintColorDark?;
    private tintColorPale?;
    private warningColorLight?;
    private warningColorDark?;
    private warningColorPale?;
    private dangerColorLight?;
    private dangerColorDark?;
    private dangerColorPale?;
    private successColorLight?;
    private successColorDark?;
    private successColorPale?;
    private complimentaryColorLight?;
    private complementaryColorDark?;
    private complementaryColorPale?;
    private mode;
    private willBeSet;
    constructor(props: ReactStylusProps);
    setMode(mode: ModeSelect): void;
    setWhatIsSet(isSet: IsSet): void;
    whatIsSet(): IsSet;
    getMode(): string;
    getColors(): ColorsMode | void;
    getBackgroundColor(): string | void;
    getTextColor(): string | void;
    getTint(): string | void;
    getComplementaryColors(): string | void;
    getColorsByMode(): ColorsByMode | void;
    getStatusColors(): StatusColors | void;
}
